# Generated by Django 5.2.17 on 2026-09-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ATTENDANT', 'Atendente'), ('ADMIN', 'Administrador do hotel')], default='ATTENDANT', help_text='ATTENDANT opera o balcão; ADMIN também publica cadastros administrativos.', max_length=10),
        ),
    ]
