# Generated by Django 5.2.17 on 2026-09-03 21:28

from django.db import migrations, models

# UniqueConstraint nomeada: a traducao de IntegrityError casa por nome.


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="document",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Reserva pendente"),
                    ("CHECKED_IN", "Hospede no hotel"),
                    ("CHECKED_OUT", "Finalizada"),
                    ("CANCELLED", "Cancelada"),
                ],
                default="PENDING",
                max_length=11,
            ),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(fields=("document",), name="guest_document_unique"),
        ),
    ]
