# Generated by Django 5.2.17 on 2026-09-03 22:27
#
# M2M implicito: unicidade (reservation, guest) vem da tabela intermediaria.
# "acompanhante em duas estadias ativas" nao tem constraint cross-table
# sem denormalizar status; a autoridade e o lock de _lock_people.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0008_room_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="companions",
            field=models.ManyToManyField(
                blank=True, related_name="companion_reservations", to="hotel.guest"
            ),
        ),
    ]
