# Generated by Django 5.2.17 on 2026-09-03 22:27

# Acompanhantes da reserva. M2M IMPLICITO: a tabela intermediaria do Django
# ja traz a unicidade `(reservation, guest)` de graca, e nao ha atributo por
# vinculo (papel, idade) que justifique um `through` explicito.
#
# Nao ha constraint cross-table possivel para "um acompanhante nao pode estar
# em duas estadias ativas" sem denormalizar `status` na tabela intermediaria; a
# autoridade dessa invariante e o lock ordenado de `_lock_people` mais a guarda
# de leitura, e isso esta declarado no RESUMO 5.2.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_room_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='companions',
            field=models.ManyToManyField(blank=True, related_name='companion_reservations', to='hotel.guest'),
        ),
    ]
