# Literais escritos aqui — migration nao importa DEFAULT_RATES (passado nao
# muda com o codigo). effective_from e sentinela em 2000: testes congelam o
# relogio em 2025 e o seed faz check-in "ontem".

# Generated by Django 5.2.17 on 2026-09-06 04:14

from datetime import UTC, datetime
from decimal import Decimal

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models

BOOTSTRAP = {
    "weekday_rate": Decimal("120.00"),
    "weekend_rate": Decimal("180.00"),
    "weekday_park": Decimal("15.00"),
    "weekend_park": Decimal("20.00"),
    "late_fee_factor": Decimal("0.5"),
    "checkin_opens": "14:00",
    "checkout_limit": "12:00",
    "note": "tarifa do briefing (bootstrap)",
}

SENTINEL_EFFECTIVE_FROM = datetime(2000, 1, 1, 0, 0, tzinfo=UTC)


def create_bootstrap_policy(apps, schema_editor):
    PricingPolicy = apps.get_model("billing", "PricingPolicy")
    # `get_or_create` e nao `create`: o `flush` transacional da suite de teste
    # nao restaura dado de migration, e a fixture autouse chama a mesma chave.
    PricingPolicy.objects.get_or_create(
        effective_from=SENTINEL_EFFECTIVE_FROM,
        defaults=BOOTSTRAP,
    )


def drop_bootstrap_policy(apps, schema_editor):
    PricingPolicy = apps.get_model("billing", "PricingPolicy")
    PricingPolicy.objects.filter(effective_from=SENTINEL_EFFECTIVE_FROM).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("weekday_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weekend_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weekday_park", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weekend_park", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "late_fee_factor",
                    models.DecimalField(decimal_places=4, default=Decimal("0.5"), max_digits=5),
                ),
                ("checkin_opens", models.TimeField()),
                ("checkout_limit", models.TimeField()),
                ("effective_from", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("weekday_rate__gte", 0),
                            ("weekend_rate__gte", 0),
                            ("weekday_park__gte", 0),
                            ("weekend_park__gte", 0),
                            ("late_fee_factor__gte", 0),
                        ),
                        name="policy_money_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("checkout_limit__lte", models.F("checkin_opens"))),
                        name="policy_checkout_before_checkin",
                    ),
                ],
            },
        ),
        migrations.RunPython(create_bootstrap_policy, drop_bootstrap_policy),
    ]
