# Generated by Django 5.2.17 on 2026-09-06 04:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Em aberto'), ('CLOSED', 'Fechada'), ('PAID', 'Paga')], default='OPEN', max_length=6)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__isnull', True), ('total_amount__gte', 0), _connector='OR'), name='account_total_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'OPEN'), ('closed_at__isnull', True), ('total_amount__isnull', True)), models.Q(('status__in', ['CLOSED', 'PAID']), ('closed_at__isnull', False), ('total_amount__isnull', False)), _connector='OR'), name='account_closed_is_complete')],
            },
        ),
        migrations.CreateModel(
            name='AccountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DAILY', 'Diária'), ('PARKING', 'Vaga'), ('LATE_FEE', 'Multa de checkout tardio'), ('EXTRA', 'Lançamento avulso')], max_length=8)),
                ('service_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=140)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=7)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.account')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_lines_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['service_date', 'kind', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='accountline_quantity_non_negative'), models.CheckConstraint(condition=models.Q(('unit_amount__gte', 0), ('amount__gte', 0)), name='accountline_money_non_negative'), models.UniqueConstraint(condition=models.Q(('kind__in', ['DAILY', 'PARKING'])), fields=('account', 'kind', 'service_date'), name='accountline_one_per_kind_date'), models.UniqueConstraint(condition=models.Q(('kind', 'LATE_FEE')), fields=('account',), name='accountline_one_late_fee')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Dinheiro'), ('CARD', 'Cartão'), ('PIX', 'Pix'), ('OTHER', 'Outro')], max_length=8)),
                ('paid_at', models.DateTimeField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='billing.account')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paid_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative')],
            },
        ),
    ]
