# Generated by Django 5.2.17 on 2026-09-06 04:14

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # pg_trgm ANTES dos indices: os GinIndex funcionais de Guest dependem da
        # classe de operadores gin_trgm_ops (SPEC 1.4).
        TrigramExtension(),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('document', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name', 'id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('full_name'), name='gin_trgm_ops'), name='guest_name_trgm_upper'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('document'), name='gin_trgm_ops'), name='guest_document_trgm_upper'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('phone'), name='gin_trgm_ops'), name='guest_phone_trgm_upper')],
                'constraints': [models.UniqueConstraint(fields=('document',), name='guest_document_unique')],
            },
        ),
    ]
