# Generated by Django 5.2.17 on 2026-09-06 04:24

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import hotel.reservations.models
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_account_ledger'),
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # btree_gist antes do EXCLUDE: resv_room_no_overlap junta btree (room)
        # e gist (daterange) no mesmo indice.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('has_vehicle', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Reserva pendente'), ('CHECKED_IN', 'Hospede no hotel'), ('CHECKED_OUT', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=11)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='billing.account')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_cancelled', to=settings.AUTH_USER_MODEL)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_checked_out', to=settings.AUTH_USER_MODEL)),
                ('companions', models.ManyToManyField(blank=True, related_name='companion_reservations', to='guests.guest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_created', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guest')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='billing.pricingpolicy')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.room')),
            ],
            options={
                'ordering': ['checkin_date', 'id'],
                'indexes': [models.Index(fields=['status', 'checkin_date'], name='resv_status_checkin')],
                'constraints': [models.CheckConstraint(condition=models.Q(('checkout_date__gt', models.F('checkin_date'))), name='resv_checkout_after_checkin'), models.UniqueConstraint(condition=models.Q(('status', 'CHECKED_IN')), fields=('guest',), name='resv_one_active_per_guest'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['PENDING', 'CHECKED_IN'])), expressions=[('room', '='), (hotel.reservations.models.DateRange('checkin_date', 'checkout_date', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='resv_room_no_overlap'), models.UniqueConstraint(condition=models.Q(('status', 'CHECKED_IN')), fields=('room',), name='resv_one_active_per_room'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CANCELLED']), ('policy__isnull', False), _connector='OR'), name='resv_active_has_policy'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'CHECKED_OUT'), _negated=True), ('checked_out_at__isnull', False), _connector='OR'), name='resv_checked_out_complete'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['CHECKED_IN', 'CHECKED_OUT']), ('account__isnull', False)), models.Q(('status__in', ['PENDING', 'CANCELLED']), ('account__isnull', True)), _connector='OR'), name='resv_account_matches_status')],
            },
        ),
    ]
