# Generated by Django 5.2.17 on 2026-09-06 04:14

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import hotel.reservations.models
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # btree_gist antes do EXCLUDE: resv_room_no_overlap junta btree (room)
        # e gist (daterange) no mesmo indice.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('has_vehicle', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Reserva pendente'), ('CHECKED_IN', 'Hospede no hotel'), ('CHECKED_OUT', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=11)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('total_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_parking', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_fee_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Dinheiro'), ('CARD', 'Cartão'), ('PIX', 'Pix'), ('OTHER', 'Outro')], max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_cancelled', to=settings.AUTH_USER_MODEL)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_checked_out', to=settings.AUTH_USER_MODEL)),
                ('companions', models.ManyToManyField(blank=True, related_name='companion_reservations', to='guests.guest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_created', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guest')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_paid', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='billing.pricingpolicy')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.room')),
            ],
            options={
                'ordering': ['checkin_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='reservations.reservation')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'checkin_date'], name='resv_status_checkin'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('checkout_date__gt', models.F('checkin_date'))), name='resv_checkout_after_checkin'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CHECKED_IN')), fields=('guest',), name='resv_one_active_per_guest'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['PENDING', 'CHECKED_IN'])), expressions=[('room', '='), (hotel.reservations.models.DateRange('checkin_date', 'checkout_date', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='resv_room_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CHECKED_IN')), fields=('room',), name='resv_one_active_per_room'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CANCELLED']), ('policy__isnull', False), _connector='OR'), name='resv_active_has_policy'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CHECKED_OUT'), _negated=True), models.Q(('checked_out_at__isnull', False), ('total_amount__isnull', False)), _connector='OR'), name='resv_checked_out_complete'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_at__isnull', True), ('payment_method__isnull', True), ('paid_by__isnull', True)), models.Q(('paid_at__isnull', False), ('payment_method__isnull', False), ('paid_by__isnull', False)), _connector='OR'), name='resv_payment_complete'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('paid_at__isnull', True), ('status', 'CHECKED_OUT'), _connector='OR'), name='resv_paid_requires_checked_out'),
        ),
        migrations.AddConstraint(
            model_name='statementline',
            constraint=models.UniqueConstraint(fields=('reservation', 'date'), name='stmtline_unique_date'),
        ),
    ]
